language: python
python:
    - "2.6"
    - "2.7"

env:
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.8.2

install:
    - python setup.py develop
    - pip install --allow-all-external django-evolution
    - pip install kgb 'Markdown>=2.4.0,<2.4.999' Pygments
    - pip install https://github.com/beanbaginc/django-evolution/archive/master.zip
    - pip install -q Django==$DJANGO_VERSION

script:
    - python ./tests/runtests.py
